src/main/java/com/hurontg/libms/domain/Book.java
package com.hurontg.libms.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
@Table(name = "BOOK")
public class Book extends BaseEntity implements Auditable {
	/**
	 * 
	 */
	@SuppressWarnings("unused")
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
	private Long id;
	private String title;
	private String isbn;
	private double cost;
	private Date published;
	private String keywords;
	private boolean available = false;
	private Publisher publisher;
	private List<BookCopy> copies = new ArrayList<BookCopy>();

	private List<Author> authors = new ArrayList<Author>();

	/**
	 * 
	 */
	public Book() {
	}

	public Book(Integer id) {
		this.id = new Long(id);
	}

	/**
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "BOOK_ID")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "TITLE", nullable = false)
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "COST")
	public double getCost() {
		return cost;
	}

	public void setCost(double cost) {
		this.cost = cost;
	}

	@Column(name = "ISBN", unique = true, nullable = false)
	public String getIsbn() {
		return isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@DateTimeFormat(pattern = "MM/dd/yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_PUBLISHED", nullable = false)
	public Date getPublished() {
		return published;
	}

	public void setPublished(Date published) {
		this.published = published;
	}

	@Column(name = "KEYWORDS")
	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PUBLISHER_ID", nullable = false, foreignKey = @ForeignKey(name = "FK__PUBLISHER_PUBLISHER_ID"))
	public Publisher getPublisher() {
		return publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	@ManyToMany
	@JoinTable(name = "BOOK_AUTHOR", joinColumns = { @JoinColumn(name = "BOOK_ID") }, inverseJoinColumns = { @JoinColumn(name = "AUTHOR_ID") })
	public List<Author> getAuthors() {
		return authors;
	}

	public void setAuthors(List<Author> authors) {
		this.authors = authors;
	}

	@JsonIgnore
	@OneToMany(cascade = { CascadeType.PERSIST, CascadeType.MERGE,
			CascadeType.REMOVE }, orphanRemoval = true, mappedBy = "book")
	public List<BookCopy> getCopies() {
		return copies;
	}

	public void setCopies(List<BookCopy> copies) {
		this.copies = copies;
	}

	@Transient
	public String getAuthorNames() {
		StringBuilder sb = new StringBuilder();
		for (Author a : authors) {
			sb.append(a.getFirstName()).append(" ").append(a.getLastName());
		}
		return sb.toString();
	}

	/**
     * 
     */
	@Override
	public String toString() {
		StringBuilder result = new StringBuilder();
		String NEW_LINE = System.getProperty("line.separator");

		result.append(this.getClass().getName()).append(" Object {")
				.append(NEW_LINE);
		result.append(" id: ").append(id).append(NEW_LINE);
		result.append(" Title: ").append(title).append(NEW_LINE);
		result.append(" ISBN: ").append(isbn).append(NEW_LINE);
		result.append(" Date Published: ").append(published).append(NEW_LINE);
		result.append(" Cost: ").append(cost).append(NEW_LINE);
		result.append(" Available: ").append(available).append(NEW_LINE);

		result.append(NEW_LINE).append("}");

		return result.toString();
	}

	public void setAvailable(boolean b) {
		available = b;

	}

	@Transient
	public boolean isAvailable() {
		return available;
	}
}

src/main/java/com/hurontg/libms/domain/Car.java
package com.hurontg.libms.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "CAR")
public class Car {

	/**
	 * 
	 */
	private Long id;
	private String make;
	private String model;
	private String color;
	private Integer doors;

	/**
	 * 
	 */
	public Car() {
	}

	public Car(Integer id) {
		this.id = new Long(id);
	}

	/**
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "CAR_ID")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "MAKE")
	public String getMake() {
		return make;
	}

	public void setMake(String make) {
		this.make = make;
	}

	@Column(name = "MODEL")
	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "COLOR")
	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "DOORS")
	public Integer getDoors() {
		return doors;
	}

	public void setDoors(Integer doors) {
		this.doors = doors;
	}

}

src/main/java/com/hurontg/libms/mvc/BookController.java
package com.hurontg.libms.mvc;

import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import org.slf4j.ext.XLogger;
import org.slf4j.ext.XLoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.hurontg.common.exception.AppServiceException;
import com.hurontg.libms.domain.AuthUser;
import com.hurontg.libms.domain.Author;
import com.hurontg.libms.domain.Book;
import com.hurontg.libms.domain.Publisher;
import com.hurontg.libms.service.AuthorService;
import com.hurontg.libms.service.BookService;
import com.hurontg.libms.service.PublisherService;
import com.hurontg.libms.service.UserService;

@Controller
public class BookController extends BaseController {

	/**
	 * 
	 */
	private XLogger logger = XLoggerFactory.getXLogger(BookController.class
			.getName());

	@Inject
	private BookService bookSvc;
	@Inject
	private PublisherService pubSvc;
	@Inject
	private AuthorService authSvc;
	@Inject
	private UserService userSvc;

	@RequestMapping(value = { "/books" }, method = RequestMethod.GET)
	public String showBooksMainPage(Model model) throws Exception {
		try {
		List<Book> books = bookSvc.getBooks();
		model.addAttribute("books", books);
		
		List<AuthUser> members = userSvc.loadMembers();
		model.addAttribute("members", members);
		} catch (AppServiceException e) {
			logger.error("Error while retrieving Books", e);
		}
		return "book-main";
	}

	@RequestMapping(value = { "/books/new" }, method = RequestMethod.GET)
	public String showBookEntryForm(Model model) throws Exception {
		List<Publisher> pubs = pubSvc.findAll();
		model.addAttribute("publishers", pubs);

		List<Author> authors = authSvc.findAll();
		model.addAttribute("authors", authors);

		Book book = new Book();
		model.addAttribute("book", book);

		return "book-new";
	}

	@RequestMapping(value = { "/books/save" }, method = RequestMethod.POST)
	public String saveNewBook(@Valid Book book, BindingResult result,
			HttpServletRequest request) throws Exception {
		if (result.hasErrors()) {
			return "book-new";
		} else {
			bookSvc.createBook(book);

			return "redirect:/books";
		}
	}

	@RequestMapping(value = { "/books/checkout" }, method = RequestMethod.POST)
	public String checkoutBook(	HttpServletRequest request) throws Exception {
		Long bookId = Long.parseLong(request.getParameter("book.id"));
		Long memberId = Long.parseLong(request.getParameter("member.id"));
		bookSvc.checkout(bookId, memberId);
		return "redirect:/books";
		
	}
	
	@RequestMapping(value = { "/books/search" }, method = RequestMethod.POST)
	public String searchBooks(HttpServletRequest request) throws Exception {
		Map<java.lang.String,java.lang.String[]> formData = request.getParameterMap();
		String[] searchQuery = formData.get("q");
		List<Book> books = bookSvc.searchBooks(searchQuery[0]);

		request.setAttribute("books", books);
		return "book-main";
	}
	
	@RequestMapping(value = { "/books/return" }, method = RequestMethod.GET)
	public String returnBook(HttpServletRequest request) throws Exception {
		Long borrowedItemId = Long.parseLong(request.getParameter("borrowedItemId"));
		bookSvc.returnBook(borrowedItemId);
		
		return "redirect:/home";
	}
	
	/*
	 * Ajax
	 */
	@RequestMapping(value = { "/public/ajaxdemo" }, method = RequestMethod.GET)
	public String ajaxDemoPage(HttpServletRequest request) throws Exception {
		return "tutorial/ajax/demopage.jsp";
	}
	
	@RequestMapping(value = { "/public/ajax/simpletextline" }, method = RequestMethod.GET)
	public String ajaxReturnSimpleLine(HttpServletRequest request) throws Exception {
		request.setAttribute("serverTime", new Date());
		return "tutorial/ajax/simple1.jsp";
	}
	
	@RequestMapping(value = { "/public/ajax/dynamicontent" }, method = RequestMethod.GET)
	public String ajaxBookTable(HttpServletRequest request) throws Exception {
		List<Book> books = bookSvc.getBooks();
		request.setAttribute("books", books);
		return "tutorial/ajax/booktable.jsp";
	}
	
	@RequestMapping(value = { "/public/ajax/formsubmit1" }, method = RequestMethod.POST)
	public /*ResponseEntity<String>*/ String ajaxSubmitFormHandler1(HttpServletRequest request, HttpServletResponse resp) throws Exception {
		Map<String, String[]> requestParams = request.getParameterMap();
		
		boolean simulateError = false;
		for(Map.Entry<String, String[]> entry : requestParams.entrySet()) {
			String name = entry.getKey();
			String[] value = entry.getValue();
			
			logger.error(name + " : " + value[0]);
			
			if (name.equals("simulate-error")) {
				simulateError = true;
			}
		}
		
		if (simulateError) {
//			resp.setStatus(sc);
//			return new ResponseEntity<String>("Error encountered on server!",  HttpStatus.INTERNAL_SERVER_ERROR);
		}
//		return new ResponseEntity<String>("Form successfully processed!", HttpStatus.OK);
		List<Book> books = bookSvc.getBooks();
		request.setAttribute("books", books);
		return "tutorial/ajax/booktable.jsp";
				
	}
	
	
	// @RequestMapping(value = { "/displayPublisherUpdateForm" }, method =
	// RequestMethod.GET)
	// public String showPublisherUpdateForm(HttpServletRequest request)
	// throws Exception {
	// String id = request.getParameter("bookId");
	// Long bookId = Long.parseLong(id);
	// Publisher book = bookSvc.findById(bookId);
	//
	// request.setAttribute("book", book);
	// return "book/bookUpdateForm.jsp";
	// }

	// @RequestMapping(value = { "/displayPublisherUpdateForm" }, method =
	// RequestMethod.GET)
	// public String showPublisherUpdateForm(HttpServletRequest request)
	// throws Exception {
	// String id = request.getParameter("bookId");
	// Long bookId = Long.parseLong(id);
	// Publisher book = bookSvc.findById(bookId);
	//
	// request.setAttribute("book", book);
	// return "book/book.jsp";
	// }

	// @RequestMapping(value = { "/updatePublisher" }, method =
	// RequestMethod.POST)
	// public String updatePublisher(HttpServletRequest request) throws
	// Exception {
	// String id = request.getParameter("id");
	// String name = request.getParameter("name");
	// String email = request.getParameter("email");
	// String phone = request.getParameter("phone");
	//
	// Publisher p = new Publisher(Long.parseLong(id), name, email, phone);
	// bookSvc.update(p);
	//
	// return "redirect:/books";
	// }

	// @RequestMapping(value = { "/updatePublisher" }, method =
	// RequestMethod.POST)
	// public String updatePublisher(@ModelAttribute Publisher book,
	// HttpServletRequest request) throws Exception {
	// bookSvc.update(book);
	//
	// return "redirect:/books";
	// }
	//
	// @RequestMapping(value = { "/deletePublisher" }, method =
	// RequestMethod.GET)
	// public String deletePublisher(HttpServletRequest request) throws
	// Exception {
	// String id = request.getParameter("bookId");
	// bookSvc.delete(Long.parseLong(id));
	// return "redirect:/books";
	// }

}

src/main/webapp/WEB-INF/jsp/book/bookEntryForm.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>

<script type="text/javascript"
	src="<c:url value='/resources/js/libms/book.js' />"></script>
<c:url value="/books/save" var="axion" />

<div class="row">
	<div class="col-xs-4">
		<form:form id="book-form" modelAttribute="book" method="post"
			action="${axion}">
			<div class="form-group">
				<label for="title">Title</label>
				<form:input path="title" class="form-control" />
				<form:errors path="title" cssClass="text-danger" />
			</div>
			<div class="form-group">
				<label for="isbn">ISBN</label>
				<form:input path="isbn" class="form-control" />
				<form:errors path="isbn" cssClass="text-danger" />
			</div>
			<div class="form-group">
				<label for="published">Date Published</label>
				<form:input path="published" class="form-control"
					id="published-date" autocomplete="false" />
				<form:errors path="published" cssClass="text-danger" />
			</div>
			<div class="form-group">
				<label for="keywords">Keywords</label>
				<form:input path="keywords" class="form-control" />
			</div>
			<div class="form-group">
				<label for="keywords">Publisher</label>
				<form:select path="publisher.id" items="${publishers}"
					itemLabel="name" itemValue="id" class="form-control" />
			</div>

			<div class="form-group">
				<label for="keywords">Authors</label>
				<form:select path="authors[0].id" items="${authors}"
					itemLabel="name" itemValue="id" class="form-control" />
			</div>

			<button type="button" class="btn btn-default" id="book-form-submit">Submit</button>
		</form:form>

	</div>

</div>

src/main/webapp/WEB-INF/jsp/book/books.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="sec"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<script type="text/javascript"
    src="<c:url value='/resources/js/libms/book.js' />"></script>
    
<c:url value="/books/search" var="searchUrl"/>
<div class="row">
<div class="col-xs-4">

<form id="book-search-form" action="${searchUrl}" method="post">
  <div class="input-group">    
    <input type="text" name = "q" id="book-search-query" class="form-control" aria-label="Text input with segmented button dropdown" autocomplete="off">
    <div class="input-group-btn">
      <button type="button" id="book-search-button" class="btn btn-default">Search</button>
      <sec:authorize access="hasRole('ROLE_STAFF')">      
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-right" role="menu">        
        <li><a href='<c:url value="/books/new" />'>New Book</a>        
      </ul>
      </sec:authorize>
    </div>
    
  </div><!-- /.input-group -->
  </form>
</div>
</div>      
<div class="row top20">
<div class="col-xs-8">
<table class="table table-bordered table-striped table-hover table-condensed compact-data-table">
<tr>
    <th>ID</th>
    <th>Title</th>
    <th>ISBN</th>
    <th>Date Published</th>
    <th>Keywords</th>
    <th>Author</th>
    <th>Publisher</th>  
    <th>Available</th>
    <th><br/></th>    
</tr>

<c:forEach items="${books}" var="book">
	<tr>
		<td><a href='<c:url value="/books/edit?bookId=${book.id}"/>'>${book.id}</a></td>
		<td><c:out value="${book.title}" /></td>
		<td><c:out value="${book.isbn}" /></td>
		<td><c:out value="${book.published}" /></td>		
		<td><c:out value="${book.keywords}" /></td>
		<td><c:out value="${book.authorNames}" /></td>
		<td><c:out value="${book.publisher.name}" /></td>		
		<td>
		  <c:choose>
		   <c:when test="${book.available}">
		    On Shelf
		   </c:when>
		   <c:otherwise>
		    Not available
		   </c:otherwise>
		  </c:choose>
		</td>
		<td><a href='<c:url value="/delete?bookId=${book.id}"/>'>Delete</a></td>
		
	</tr>
</c:forEach>

</table>
</div>
<sec:authorize access="hasRole('ROLE_STAFF')">
<div class="col-xs-4">
<div class="panel panel-default" id="equipments-table-panel">
<div class="panel-heading clearfix">
   <strong>Checkout Books</strong>
</div>
<div class="panel-body">     
<c:url value="/books/checkout" var="frmAction" />
  <form id="book-checkout-form" method="post" action="${frmAction}">
      <div class="form-group">
        <label for="title">Books</label>
        <select name="book.id" class="form-control">
        <c:forEach items="${books}" var="book">
          <c:if test="${book.available}">
            <option value="${book.id}">${book.title} - ${book.authors[0].name}</option>
          </c:if>
        </c:forEach>
        </select>            
      </div>
      <div class="form-group">
        <label for="title">Members</label>
        <select name="member.id" class="form-control">
        <c:forEach items="${members}" var="member">
          <option value="${member.id}">${member.firstName} - ${member.lastName}</option>
        </c:forEach>
        </select>        
      </div>
      <div class="form-group pull-right">
        <button type="submit" class="btn btn-primary" id="book-checkout-form-submit">Checkout</button>
      </div>
   </form>
</div>
</div>
</div>
</sec:authorize>
</div>

src/main/webapp/WEB-INF/jsp/book/car.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<br/><br/><br/>
<form:form modelAttribute="car" method="post">
   <div class="form-group">
      <label for="title">Make</label>
      <form:input path="make"/>         
   </div>
   <div class="form-group">
      <label for="isbn">Model (Long Label)</label>
      <form:input path="model"/>
   </div>
   <div class="form-group">
      <label for="isbn">Color</label>
      <form:input path="color"/>
   </div>
   <button type="submit" class="btn btn-default">Submit</button>
</form:form>
      